// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfSs7QrVXgEfx2jbTbevmOBKhatgTAeLE',
    appId: '1:1026924865921:web:a4b462e53590e6e79a2080',
    messagingSenderId: '1026924865921',
    projectId: 'app-habits-21766',
    authDomain: 'app-habits-21766.firebaseapp.com',
    databaseURL: 'https://app-habits-21766-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-habits-21766.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzR3IOhLbTsE5yWZqAHkXdKusoWu6l4oo',
    appId: '1:1026924865921:android:de17b8883beb0c569a2080',
    messagingSenderId: '1026924865921',
    projectId: 'app-habits-21766',
    databaseURL: 'https://app-habits-21766-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-habits-21766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCiJwIQ8OwvYu1Mmu2MLqh2nq0aDA3Bs',
    appId: '1:1026924865921:ios:4451ecca4d11dda59a2080',
    messagingSenderId: '1026924865921',
    projectId: 'app-habits-21766',
    databaseURL: 'https://app-habits-21766-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-habits-21766.appspot.com',
    iosClientId: '1026924865921-jda8g9n7v9622djionb8kdidhakao89k.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingHabits',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMCiJwIQ8OwvYu1Mmu2MLqh2nq0aDA3Bs',
    appId: '1:1026924865921:ios:4451ecca4d11dda59a2080',
    messagingSenderId: '1026924865921',
    projectId: 'app-habits-21766',
    databaseURL: 'https://app-habits-21766-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-habits-21766.appspot.com',
    iosClientId: '1026924865921-jda8g9n7v9622djionb8kdidhakao89k.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackingHabits',
  );
}
